
volumes:
  database-vol:
    name: "database-vol"

services:
  
  database:
    image: database:1.0.0
    container_name: ${DATABASE_HOST}
    build: 
      context: ./database
      dockerfile: Dockerfile 
    env_file:
      - .env 
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - database-vol:/data/db

  api:
    image: recipouir:1.0.0
    container_name: reciapi
    volumes:
      - ${LOCAL_CERT}:/certs
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    env_file:
      - ./.env
    ports:
      - ${API_PORT}:443
    depends_on:
      - database